# Generated by Django 4.2.7 on 2023-11-01 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='media_files',
        ),
        migrations.AddField(
            model_name='mediafile',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='api.item'),
        ),
    ]
