# Generated by Django 4.2.7 on 2023-11-01 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_item_media_files_mediafile_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appteenyuser',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='appteenyuser',
            name='lastname',
        ),
    ]
