# Generated by Django 4.2.7 on 2023-11-02 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_appteenyuser_firstname_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='Items',
        ),
    ]
