# Generated by Django 4.2.7 on 2023-11-02 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_model_items_modeltype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='features',
            field=models.CharField(max_length=1000),
        ),
    ]
