# Generated by Django 4.2.7 on 2023-11-04 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_items_features'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='previous_users',
        ),
        migrations.AddField(
            model_name='ownershiphistory',
            name='isOwner',
            field=models.BooleanField(default=False),
        ),
    ]
