# Generated by Django 4.2.7 on 2023-11-04 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_items_previous_users_ownershiphistory_isowner'),
    ]

    operations = [
        migrations.AddField(
            model_name='appteenyuser',
            name='activation_key',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='appteenyuser',
            name='is_active',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
